### ISSUE TITLE
License text

### ISSUE THREAD

**Issue by firefly-cpp** [Aniket-Pradhan/Aniket-Pradhan.github.io#1]
Hi Aniket!

As I told you last year, your website is extremely interesting as well as unique. Can I ask you to commit the license text for this source code? I would like to use some bits of your website, especially imitated man page :smile:

**Comment by Aniket-Pradhan** [comment]
Hey Iztok!

I have added the license text and the URL to the license on the webpage. The license in itself is "quite" permissive, so feel free to use any elements you want to. 😛 

Thanks a lot for letting me know.

**Comment by firefly-cpp** [comment]
Many thanks @Aniket-Pradhan!
